version: '3.8'

services:
  # Database per User Service
  postgres-users:
    image: postgres:15-alpine
    container_name: fantacontratti-postgres-users
    environment:
      POSTGRES_DB: fantacontratti_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
      - ./databases/users/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fantacontratti-network

  # Database per Contract Service
  postgres-contracts:
    image: postgres:15-alpine
    container_name: fantacontratti-postgres-contracts
    environment:
      POSTGRES_DB: fantacontratti_contracts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_contracts_data:/var/lib/postgresql/data
      - ./databases/contracts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fantacontratti-network

  # Redis per caching e sessioni
  redis:
    image: redis:7-alpine
    container_name: fantacontratti-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fantacontratti-network

  # Zookeeper per Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: fantacontratti-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - fantacontratti-network

  # Kafka Message Broker
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: fantacontratti-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - fantacontratti-network

  # Kafka UI per gestione e monitoraggio
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: fantacontratti-kafka-ui
    depends_on:
      - kafka
    ports:
      - "9021:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - fantacontratti-network

volumes:
  postgres_users_data:
  postgres_contracts_data:
  redis_data:

networks:
  fantacontratti-network:
    driver: bridge