version: '3.8'

services:
  # Database per User Service con configurazione TDD-friendly
  postgres-users:
    image: postgres:15-alpine
    container_name: fantacontratti-postgres-users-tdd
    environment:
      POSTGRES_DB: fantacontratti_users
      POSTGRES_USER: postgres
      # No password for TDD simplicity
      # POSTGRES_HOST_AUTH_METHOD configures all auth to trust
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
      - ../infrastructure/databases/users/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - fantacontratti-network
    # Simple command without auth complexities
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fantacontratti_users"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Database per Contract Service
  postgres-contracts:
    image: postgres:15-alpine
    container_name: fantacontratti-postgres-contracts
    environment:
      POSTGRES_DB: fantacontratti_contracts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--auth=md5"
    ports:
      - "5433:5432"
    volumes:
      - postgres_contracts_data:/var/lib/postgresql/data
      - ../infrastructure/databases/contracts/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - fantacontratti-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fantacontratti_contracts"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis per caching e sessioni
  redis:
    image: redis:7-alpine
    container_name: fantacontratti-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fantacontratti-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Zookeeper per Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: fantacontratti-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - fantacontratti-network
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'ruok' | nc localhost 2181"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Kafka Message Broker
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: fantacontratti-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - fantacontratti-network
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 5

  # Kafka UI per gestione e monitoraggio
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: fantacontratti-kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "9021:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - fantacontratti-network

volumes:
  postgres_users_data:
  postgres_contracts_data:
  redis_data:

networks:
  fantacontratti-network:
    driver: bridge